export type ProviderStatus = "active" | "limited" | "needs_api_key" | "planned";
export type ProviderCategory =
  | "Discovery"
  | "DNS & Subdomains"
  | "Identities & Emails"
  | "Social Presence"
  | "Breaches & Leaks"
  | "Infrastructure & Exposure"
  | "Technology Fingerprinting";
export type ProviderEvidence =
  | "websites"
  | "subdomains"
  | "dns"
  | "whois"
  | "ssl"
  | "hosting"
  | "ports"
  | "tech"
  | "emails"
  | "social"
  | "repos"
  | "breaches"
  | "certificates";
export type ProviderAuth = "none" | "optional" | "required";
export type ProviderReliability = "stable" | "medium" | "fragile";

export interface OsintProvider {
  id: string;
  label: string;
  category: ProviderCategory;
  status: ProviderStatus;
  evidence: ProviderEvidence[];
  auth: ProviderAuth;
  cost: string;
  reliability: ProviderReliability;
  implementation: "internal" | "external";
  selectable: boolean;
  defaultSelected: boolean;
  details: string;
  whyKeep: string;
  limits: string;
}

export const osintProviders: OsintProvider[] = [
  {
    id: "direct_dns",
    label: "Direct DNS",
    category: "DNS & Subdomains",
    status: "active",
    evidence: ["dns", "subdomains"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "internal",
    selectable: true,
    defaultSelected: false,
    details: "A, AAAA, MX, NS, TXT, SOA, CAA, SPF, DMARC, and common subdomain checks.",
    whyKeep: "Baseline domain intelligence with strong signal and no external dependency.",
    limits: "Finds only what DNS exposes and a fixed wordlist of common subdomains.",
  },
  {
    id: "crtsh",
    label: "crt.sh",
    category: "DNS & Subdomains",
    status: "active",
    evidence: ["subdomains", "certificates", "emails", "ssl"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Certificate Transparency entries, extra subdomains, cert history, and occasional embedded emails.",
    whyKeep: "High-value passive source for subdomains and certificate visibility.",
    limits: "Coverage depends on CT logs and rarely yields large email sets.",
  },
  {
    id: "whois",
    label: "WHOIS",
    category: "Discovery",
    status: "active",
    evidence: ["whois"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "internal",
    selectable: true,
    defaultSelected: true,
    details: "Registrar, registration dates, status, nameservers, org, and country data.",
    whyKeep: "Low-cost baseline attribution and domain-age context.",
    limits: "Modern privacy redaction often removes rich registrant details.",
  },
  {
    id: "ssl_inspection",
    label: "SSL Inspection",
    category: "Infrastructure & Exposure",
    status: "active",
    evidence: ["ssl", "certificates"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "internal",
    selectable: true,
    defaultSelected: false,
    details: "TLS validity, issuer, SANs, dates, wildcard status, and cert metadata.",
    whyKeep: "Strong signal for operational maturity and exposed hostnames.",
    limits: "Only covers reachable TLS endpoints and current certificate chain state.",
  },
  {
    id: "ipwhois",
    label: "IP / ASN Enrichment",
    category: "Infrastructure & Exposure",
    status: "active",
    evidence: ["hosting"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "internal",
    selectable: true,
    defaultSelected: false,
    details: "IPv4/IPv6, reverse DNS, ASN, ISP, cloud/CDN hints, and geolocation-style fields.",
    whyKeep: "Useful attribution layer for hosting and network ownership.",
    limits: "Depends on successful IP resolution and public RDAP quality.",
  },
  {
    id: "port_scan",
    label: "Port Probing",
    category: "Infrastructure & Exposure",
    status: "active",
    evidence: ["ports"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "internal",
    selectable: true,
    defaultSelected: true,
    details: "Checks a small built-in port list for commonly exposed services.",
    whyKeep: "Adds immediate exposure signal without needing Shodan or Censys.",
    limits: "Narrow port coverage and sensitive to network blocking or timeouts.",
  },
  {
    id: "tech_fingerprint",
    label: "Tech Fingerprinting",
    category: "Technology Fingerprinting",
    status: "active",
    evidence: ["tech"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "internal",
    selectable: true,
    defaultSelected: true,
    details: "Server headers, powered-by, cookies, analytics hints, CMS hints, and security headers.",
    whyKeep: "High practical value for understanding stack and security posture.",
    limits: "Header-based inference can miss hidden frameworks or be obfuscated.",
  },
  {
    id: "duckduckgo",
    label: "DuckDuckGo",
    category: "Discovery",
    status: "active",
    evidence: ["websites", "social", "emails"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Official website discovery, social-profile fallback search, and email dorking.",
    whyKeep: "Cheap multi-purpose source that improves discovery coverage quickly.",
    limits: "HTML scraping can be fragile and result quality varies by query.",
  },
  {
    id: "bing",
    label: "Bing",
    category: "Discovery",
    status: "active",
    evidence: ["websites"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Fallback search engine for official website discovery.",
    whyKeep: "Good redundancy when direct probing and DuckDuckGo are weak.",
    limits: "Currently used only for website discovery in the app.",
  },
  {
    id: "google",
    label: "Google",
    category: "Discovery",
    status: "limited",
    evidence: ["websites", "social", "emails"],
    auth: "none",
    cost: "Free",
    reliability: "fragile",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "HTML search scraping for website discovery, mention capture, email dorks, and social-profile search.",
    whyKeep: "High-value search coverage for broad mentions and identity discovery.",
    limits: "Public scraping is challenge-prone and should be treated as best effort.",
  },
  {
    id: "wikidata",
    label: "Wikidata",
    category: "Social Presence",
    status: "active",
    evidence: ["social"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Authoritative social handles when an organization entity exists.",
    whyKeep: "High-signal social enrichment when present.",
    limits: "Coverage is inconsistent for smaller or less-maintained organizations.",
  },
  {
    id: "social_probe",
    label: "Social Probe",
    category: "Social Presence",
    status: "active",
    evidence: ["social"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "internal",
    selectable: true,
    defaultSelected: false,
    details: "Direct platform probing using brand/domain-derived slugs with page-validation heuristics.",
    whyKeep: "Finds likely official profiles even when search providers do not attribute the hit cleanly.",
    limits: "Heuristic probing can produce false positives and should be reviewed with the source label.",
  },
  {
    id: "sherlock",
    label: "Sherlock",
    category: "Social Presence",
    status: "active",
    evidence: ["social"],
    auth: "none",
    cost: "Free tool",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Username-based social account discovery across many networks, used here for brand-handle discovery and near-match impersonation checks.",
    whyKeep: "Adds broader social OSINT coverage and a useful impersonation-detection angle beyond the current direct probes.",
    limits: "Username-based discovery is heuristic and should be treated as corroborating evidence, not proof of official ownership.",
  },
  {
    id: "spiderfoot",
    label: "SpiderFoot",
    category: "Discovery",
    status: "active",
    evidence: ["emails", "subdomains", "social", "hosting", "websites"],
    auth: "none",
    cost: "Free tool",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Local CLI-driven recon that can surface emails, subdomains, related URLs, and social profile clues.",
    whyKeep: "Broad OSINT collector that complements narrower providers with one local scan.",
    limits: "Can be slower than focused providers and should be normalized to avoid noisy raw output.",
  },
  {
    id: "spiderfoot_deep",
    label: "SpiderFoot Deep",
    category: "Breaches & Leaks",
    status: "active",
    evidence: ["emails", "subdomains", "social", "hosting", "breaches", "websites"],
    auth: "optional",
    cost: "Free tool",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Expanded SpiderFoot background scan for emails, breach-like signals, credential exposure hints, and possible impersonation candidates.",
    whyKeep: "Adds a slower but broader enrichment mode without replacing the lighter interactive SpiderFoot workflow.",
    limits: "Runs longer, produces noisier findings, and surfaces candidates rather than confirmed impersonation or breach ownership.",
  },
  {
    id: "theharvester",
    label: "theHarvester",
    category: "Identities & Emails",
    status: "active",
    evidence: ["emails", "subdomains"],
    auth: "optional",
    cost: "Free tool",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Aggregates passive sources like Cert Spotter, crt.sh, OTX, RapidDNS, and Urlscan.",
    whyKeep: "Fast way to widen passive email discovery with one toggle.",
    limits: "Results depend heavily on source health and local installation.",
  },
  {
    id: "recon_ng",
    label: "recon-ng",
    category: "Identities & Emails",
    status: "active",
    evidence: ["emails"],
    auth: "optional",
    cost: "Free tool",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Runs contact modules such as WHOIS POCs, PGP search, and Hunter-based enrichment.",
    whyKeep: "Useful modular email/identity framework with room to grow.",
    limits: "Value varies by installed modules and available external credentials.",
  },
  {
    id: "hunter",
    label: "Hunter",
    category: "Identities & Emails",
    status: "needs_api_key",
    evidence: ["emails"],
    auth: "required",
    cost: "Limited free, paid tiers",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Authenticated domain-search enrichment for company email addresses and patterns.",
    whyKeep: "High-signal email source when the API key is configured.",
    limits: "Coverage still depends on Hunter data quality and account limits.",
  },
  {
    id: "phonebook_cz",
    label: "Phonebook.cz",
    category: "Identities & Emails",
    status: "limited",
    evidence: ["emails"],
    auth: "optional",
    cost: "Limited free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Passive public email search endpoint for domain-linked addresses.",
    whyKeep: "Adds a distinct passive email source beyond search engines.",
    limits: "Public access is limited and may return sparse results.",
  },
  {
    id: "github_code",
    label: "GitHub Code Search",
    category: "Identities & Emails",
    status: "limited",
    evidence: ["emails", "repos"],
    auth: "optional",
    cost: "Free/limited",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Searches public code for email mentions and raw file content.",
    whyKeep: "High value for leaked or publicly referenced addresses.",
    limits: "Rate limits and API response quality vary without authentication.",
  },
  {
    id: "github_repos",
    label: "GitHub Repo Search",
    category: "Social Presence",
    status: "active",
    evidence: ["repos"],
    auth: "optional",
    cost: "Free/limited",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Discovers public repositories associated with the domain string.",
    whyKeep: "Good low-cost signal for public engineering footprint.",
    limits: "Domain-string repo search is heuristic and can include unrelated repos.",
  },
  {
    id: "hibp",
    label: "Have I Been Pwned",
    category: "Breaches & Leaks",
    status: "needs_api_key",
    evidence: ["breaches"],
    auth: "required",
    cost: "Paid for richer API use",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Authenticated breach checks and breach-hint enrichment for investigated domains.",
    whyKeep: "High-value breach signal once the API key is configured.",
    limits: "Result depth still depends on endpoint coverage and account access.",
  },
  {
    id: "hackertarget",
    label: "HackerTarget",
    category: "DNS & Subdomains",
    status: "limited",
    evidence: ["subdomains", "hosting"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Public host-search results for domains and related hosts.",
    whyKeep: "Useful lightweight passive host source for comparison against other DNS providers.",
    limits: "Free endpoint can be rate-limited and often returns only a small result set.",
  },
  {
    id: "dehashed",
    label: "DeHashed",
    category: "Breaches & Leaks",
    status: "limited",
    evidence: ["breaches"],
    auth: "required",
    cost: "Paid credits",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Current app only shows a public hint when results appear to exist.",
    whyKeep: "Strong breach-intelligence provider if authenticated later.",
    limits: "Current implementation does not retrieve full results.",
  },
  {
    id: "bevigil",
    label: "BeVigil",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "tech"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Mobile and asset OSINT with app-related exposure data.",
    whyKeep: "Potentially valuable if mobile app surface matters.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "brave",
    label: "Brave Search",
    category: "Discovery",
    status: "needs_api_key",
    evidence: ["websites", "social"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Official Brave Search API for website discovery, social corroboration, and search-based email dorking.",
    whyKeep: "Improves search resiliency without relying only on scraped HTML engines.",
    limits: "Requires an API key and result quality still depends on Brave index coverage.",
  },
  {
    id: "bufferoverun",
    label: "BufferOverrun",
    category: "DNS & Subdomains",
    status: "active",
    evidence: ["subdomains"],
    auth: "none",
    cost: "Free",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "TLS certificate-derived passive subdomain lookup via the public BufferOverrun endpoint.",
    whyKeep: "Adds certificate-based subdomain coverage with almost no setup cost.",
    limits: "Public endpoint quality varies and may not return deep coverage for every domain.",
  },
  {
    id: "builtwith",
    label: "BuiltWith",
    category: "Technology Fingerprinting",
    status: "needs_api_key",
    evidence: ["tech"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Technology stack enrichment with product-level visibility.",
    whyKeep: "Strong complement to simple header-based tech detection.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "censys",
    label: "Censys",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["subdomains", "certificates"],
    auth: "required",
    cost: "Paid credits",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Platform API certificate search using a Personal Access Token, with an organization ID when required, to surface internet-facing names tied to the target domain.",
    whyKeep: "Strong infrastructure enrichment when passive DNS alone is sparse.",
    limits: "Current implementation focuses on certificate-name enrichment and requires an org-enabled Censys account for Platform search access.",
  },
  {
    id: "criminalip",
    label: "Criminal IP",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports", "tech"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "CTI-oriented exposure and internet asset search.",
    whyKeep: "Promising exposure source for comparison against Shodan/Censys.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "dnsdumpster",
    label: "DNSDumpster",
    category: "DNS & Subdomains",
    status: "planned",
    evidence: ["subdomains", "dns"],
    auth: "optional",
    cost: "Free tier then paid",
    reliability: "fragile",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Domain research and related host discovery.",
    whyKeep: "Could add passive DNS coverage.",
    limits: "Not implemented and likely scrape-sensitive.",
  },
  {
    id: "fofa",
    label: "FOFA",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports", "tech"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Internet asset search similar to Shodan.",
    whyKeep: "Useful regional/alternative exposure coverage.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "fullhunt",
    label: "FullHunt",
    category: "DNS & Subdomains",
    status: "needs_api_key",
    evidence: ["subdomains", "hosting"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Attack-surface discovery with subdomain intelligence.",
    whyKeep: "Strong candidate for broadening asset discovery.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "hunterhow",
    label: "HunterHow",
    category: "Infrastructure & Exposure",
    status: "planned",
    evidence: ["hosting", "tech"],
    auth: "optional",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Security researcher-oriented internet search results.",
    whyKeep: "Could complement Shodan-like sources later.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "intelx",
    label: "IntelX",
    category: "Breaches & Leaks",
    status: "needs_api_key",
    evidence: ["emails", "breaches"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Leak and intelligence search across multiple datasets.",
    whyKeep: "Potentially high-value for deep breach investigation.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "leakix",
    label: "LeakIX",
    category: "Breaches & Leaks",
    status: "needs_api_key",
    evidence: ["hosting", "breaches"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Exposure and leak indexing of public assets.",
    whyKeep: "Good candidate for exposed-service and leak correlation.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "leaklookup",
    label: "Leak Lookup",
    category: "Breaches & Leaks",
    status: "needs_api_key",
    evidence: ["emails", "breaches"],
    auth: "required",
    cost: "Paid credits",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Credential and breach search service.",
    whyKeep: "Can help compare breach coverage versus HIBP and DeHashed.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "mojeek",
    label: "Mojeek",
    category: "Discovery",
    status: "needs_api_key",
    evidence: ["websites"],
    auth: "required",
    cost: "Usage-based",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Alternative search engine for discovery checks.",
    whyKeep: "Could diversify search-based discovery sources.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "netlas",
    label: "Netlas",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports", "tech"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Search platform for hosts, services, and certificates.",
    whyKeep: "Good alternative internet-exposure source.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "onyphe",
    label: "Onyphe",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Cyber defense search engine for internet assets.",
    whyKeep: "Could support high-volume exposure intelligence later.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "otx",
    label: "AlienVault OTX",
    category: "Infrastructure & Exposure",
    status: "planned",
    evidence: ["subdomains", "hosting"],
    auth: "optional",
    cost: "Free",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "OTX is used indirectly today through theHarvester but not as a first-class provider.",
    whyKeep: "Could be exposed directly later if source attribution matters.",
    limits: "Not a standalone selectable integration yet.",
  },
  {
    id: "pentesttools",
    label: "Pentest-Tools",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports", "tech"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Cloud offensive security toolkit and asset intelligence platform.",
    whyKeep: "Potentially useful for broader attack-surface workflows.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "projectdiscovery",
    label: "ProjectDiscovery Chaos",
    category: "DNS & Subdomains",
    status: "needs_api_key",
    evidence: ["subdomains"],
    auth: "required",
    cost: "Free signup then enterprise",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Maintained asset data focused on DNS and subdomain visibility.",
    whyKeep: "Strong candidate for high-signal subdomain enrichment.",
    limits: "Requires an API key and is limited to Chaos dataset coverage.",
  },
  {
    id: "rapiddns",
    label: "RapidDNS",
    category: "DNS & Subdomains",
    status: "active",
    evidence: ["subdomains"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Direct passive DNS and subdomain lookup from the public RapidDNS results page.",
    whyKeep: "Adds a direct passive DNS source beyond crt.sh and DNS brute force.",
    limits: "HTML parsing is less stable than a formal API.",
  },
  {
    id: "rocketreach",
    label: "RocketReach",
    category: "Identities & Emails",
    status: "needs_api_key",
    evidence: ["emails", "social"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Authenticated people search that can return current work emails and profile links for company-associated people.",
    whyKeep: "High-value commercial identity source when public scraping is sparse.",
    limits: "Requires API credits and results depend on RocketReach coverage for the target organization.",
  },
  {
    id: "securityscorecard",
    label: "SecurityScorecard",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "tech"],
    auth: "required",
    cost: "Requires work email / commercial",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Vendor risk and external security posture intelligence.",
    whyKeep: "May be valuable for enterprise scoring workflows.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "securitytrails",
    label: "SecurityTrails",
    category: "DNS & Subdomains",
    status: "needs_api_key",
    evidence: ["subdomains", "dns"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Historical DNS and subdomain intelligence.",
    whyKeep: "One of the highest-value passive DNS candidates.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "shodan",
    label: "Shodan",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports", "tech"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Exposed services, banners, ports, and host fingerprints.",
    whyKeep: "Very strong future source for internet exposure.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "subdomaincenter",
    label: "Subdomain Center",
    category: "DNS & Subdomains",
    status: "limited",
    evidence: ["subdomains"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Public subdomain enumeration dataset.",
    whyKeep: "Could cheaply improve subdomain coverage.",
    limits: "Public responses can be sparse or rate-limited.",
  },
  {
    id: "subdomainfinderc99",
    label: "C99 Subdomain Finder",
    category: "DNS & Subdomains",
    status: "limited",
    evidence: ["subdomains"],
    auth: "none",
    cost: "Free",
    reliability: "fragile",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Public subdomain-finder endpoint.",
    whyKeep: "Potential lightweight supplemental source.",
    limits: "Scrape-fragile public endpoint with inconsistent formatting.",
  },
  {
    id: "thc",
    label: "THC",
    category: "DNS & Subdomains",
    status: "limited",
    evidence: ["subdomains"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Free public subdomain enumeration service.",
    whyKeep: "Could add passive asset coverage with low cost.",
    limits: "Public responses can be sparse and endpoint behavior may vary.",
  },
  {
    id: "threatminer",
    label: "ThreatMiner",
    category: "Infrastructure & Exposure",
    status: "limited",
    evidence: ["subdomains", "hosting"],
    auth: "none",
    cost: "Free",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Public threat-intelligence API for domain-linked subdomains and related assets.",
    whyKeep: "Adds another low-cost passive source to compare against certificate and search-based enumeration.",
    limits: "Public responses can be sparse and service availability varies.",
  },
  {
    id: "tomba",
    label: "Tomba",
    category: "Identities & Emails",
    status: "needs_api_key",
    evidence: ["emails"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Email finding and verification service.",
    whyKeep: "Could be valuable for identity-enrichment comparisons.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "urlscan",
    label: "Urlscan",
    category: "Technology Fingerprinting",
    status: "limited",
    evidence: ["tech", "hosting", "subdomains"],
    auth: "optional",
    cost: "Free tier then paid",
    reliability: "stable",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Public search results for scanned pages, domains, and related hosts.",
    whyKeep: "Useful passive source for subdomains and externally observed web assets.",
    limits: "Free search can be rate-limited and result depth is limited.",
  },
  {
    id: "venacus",
    label: "Venacus",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting"],
    auth: "required",
    cost: "Free tier then paid",
    reliability: "medium",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Search engine for public internet intelligence.",
    whyKeep: "Worth evaluating later as an additional exposure source.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "virustotal",
    label: "VirusTotal",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["subdomains", "hosting"],
    auth: "required",
    cost: "Free tier then business",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Domain and infrastructure enrichment from VirusTotal datasets.",
    whyKeep: "Good cross-check source for asset visibility.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "whoisxml",
    label: "WhoisXML",
    category: "DNS & Subdomains",
    status: "needs_api_key",
    evidence: ["subdomains", "whois"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Subdomain and WHOIS enrichment APIs.",
    whyKeep: "Strong future candidate for structured DNS enrichment.",
    limits: "Not implemented in the current app.",
  },
  {
    id: "windvane",
    label: "Windvane",
    category: "Discovery",
    status: "limited",
    evidence: ["websites"],
    auth: "none",
    cost: "Free tier",
    reliability: "medium",
    implementation: "external",
    selectable: true,
    defaultSelected: false,
    details: "Alternative search engine for discovery testing.",
    whyKeep: "Could diversify search results if integrated later.",
    limits: "Public search behavior may be brittle and needs diagnostic notes.",
  },
  {
    id: "zoomeye",
    label: "ZoomEye",
    category: "Infrastructure & Exposure",
    status: "needs_api_key",
    evidence: ["hosting", "ports", "tech"],
    auth: "required",
    cost: "Paid",
    reliability: "stable",
    implementation: "external",
    selectable: false,
    defaultSelected: false,
    details: "Internet search engine for exposed hosts and services.",
    whyKeep: "Useful alternative to Shodan for exposure coverage.",
    limits: "Not implemented in the current app.",
  },
];

export const osintProviderIds = osintProviders.map((provider) => provider.id);

export function getSelectableProviderIds(): string[] {
  return osintProviders.filter((provider) => provider.selectable).map((provider) => provider.id);
}

export function getDefaultSelectedProviderIds(): string[] {
  return osintProviders
    .filter((provider) => provider.selectable && provider.defaultSelected)
    .map((provider) => provider.id);
}

export function isKnownProviderId(id: string): boolean {
  return osintProviderIds.includes(id);
}

export function sanitizeSelectedProviderIds(sourceIds: unknown): string[] {
  if (!Array.isArray(sourceIds)) {
    return [];
  }

  const uniqueIds = Array.from(new Set(sourceIds.filter((value): value is string => typeof value === "string")));

  return uniqueIds.filter((id) => isKnownProviderId(id));
}
